version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_SERVICES_HOST=/service/
    ports:
      - "80:80"
    networks: 
      - frontend
      - backend
  
  backend:
    image: nginx-backend
    build:
      context: ./backend
    networks: 
      - backend

networks: 
  frontend:
  backend: